name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: diegolanf/cache-npm@v3
  tests:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run ci:test
  e2e-home:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v3
      - uses: cypress-io/github-action@v6
        with:
          project: apps/home-e2e
          start: npm run ci:serve:home
          wait-on: 'http://localhost:4200'
          config: baseUrl=http://localhost:4200
  e2e-tochtli:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v3
      - uses: cypress-io/github-action@v6
        with:
          project: apps/tochtli-e2e
          start: npm run ci:serve:tochtli
          wait-on: 'http://localhost:4300'
          config: baseUrl=http://localhost:4300
  e2e-home-api:
    runs-on: ubuntu-latest
    environment: home-test
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v3
      - uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PORT: ${{env.PORT}}
          envkey_PG_HOST: ${{secrets.PG_HOST}}
          envkey_PG_DATABASE: ${{env.PG_DATABASE}}
          envkey_PG_USER: ${{secrets.PG_USER}}
          envkey_PG_PASSWORD: ${{secrets.PG_PASSWORD}}
          directory: apps/home-api
          file_name: .env
      - uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          PORT: ${{env.PORT}}
          PG_HOST: ${{secrets.PG_HOST}}
          PG_DATABASE: ${{env.PG_DATABASE}}
          PG_USER: ${{secrets.PG_USER}}
          PG_PASSWORD: ${{secrets.PG_PASSWORD}}
      - run: npm run ci:e2e:home-api
  e2e-tochtli-api:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run ci:e2e:tochtli-api
  delete-functions:
    runs-on: ubuntu-latest
    needs: [ tests, e2e-home, e2e-tochtli, e2e-home-api, e2e-tochtli-api ]
    continue-on-error: true
    steps:
      - uses: w9jds/firebase-action@master
        with:
          args: functions:delete homeApp tochtliApp --project=diego-langarica --force
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [ delete-functions ]
    steps:
      - uses: diegolanf/cache-npm@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run ci:build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
