name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: diegolanf/cache-npm@v2
      - name: Cache cypress
        id: cache-cypress
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ runner.os }}-cypress
  tests:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm run ci:test
  e2e-client:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v2
      - name: Restore cached Cypress
        id: cache-cypress-restore
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ runner.os }}-cypress
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm run ci:e2e:client
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [ tests, e2e-client ]
    steps:
      - uses: diegolanf/cache-npm@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm run ci:build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIEGO_LANGARICA }}'
          channelId: live
          projectId: diego-langarica
