name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: diegolanf/cache-npm@v2
  tests:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm run ci:test
  e2e-client:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v2
      - uses: cypress-io/github-action@v6
        with:
          project: apps/client-e2e
          start: npm run ci:serve:client
          wait-on: 'http://localhost:4200'
          config: baseUrl=http://localhost:4200
  e2e-tochtli:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v2
      - uses: cypress-io/github-action@v6
        with:
          project: apps/tochtli-e2e
          start: npm run ci:serve:client
          wait-on: 'http://localhost:4300'
          config: baseUrl=http://localhost:4300
  e2e-api:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: diegolanf/cache-npm@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run ci:e2e:api
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [ tests, e2e-client, e2e-api ]
    steps:
      - uses: diegolanf/cache-npm@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm run ci:build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
